import type { ActionDef } from './types';

export const actions: ActionDef[] = [
    {
        id: 'study',
        label: 'Study',
        emoji: '📚',
        positiveEffects: { smarts: 6 },
        negativeEffects: { happiness: -2, health: -1 },
        eventChance: 0.15,
        maxUsesPerYear: 3,
    },
    {
        id: 'exercise',
        label: 'Exercise',
        emoji: '🏃',
        positiveEffects: { health: 6, looks: 3 },
        negativeEffects: { happiness: -1, cash: -5 },
        eventChance: 0.1,
        maxUsesPerYear: 3,
    },
    {
        id: 'socialize',
        label: 'Socialize',
        emoji: '🎉',
        positiveEffects: { happiness: 8, karma: 2 },
        negativeEffects: { smarts: -1, cash: -10 },
        eventChance: 0.2,
        maxUsesPerYear: 3,
    },
    {
        id: 'work',
        label: 'Work',
        emoji: '💼',
        positiveEffects: { cash: 40 },
        negativeEffects: { happiness: -3, health: -2 },
        eventChance: 0.15,
        maxUsesPerYear: 4,
    },
    {
        id: 'rest',
        label: 'Rest',
        emoji: '😴',
        positiveEffects: { health: 5, happiness: 3 },
        negativeEffects: { smarts: -1 },
        eventChance: 0.05,
        maxUsesPerYear: 2,
    },
    {
        id: 'risky',
        label: 'Risky Choice',
        emoji: '🎲',
        positiveEffects: { happiness: 5, cash: 20 },
        negativeEffects: { karma: -5, health: -3 },
        eventChance: 0.35,
        maxUsesPerYear: 2,
    },
    {
        id: 'meditate',
        label: 'Meditate',
        emoji: '🧘',
        positiveEffects: { happiness: 5, karma: 4 },
        negativeEffects: { looks: -1 },
        eventChance: 0.05,
        maxUsesPerYear: 2,
    },
    {
        id: 'groom',
        label: 'Self-care',
        emoji: '💅',
        positiveEffects: { looks: 6, happiness: 3 },
        negativeEffects: { cash: -15, smarts: -1 },
        eventChance: 0.1,
        maxUsesPerYear: 2,
    },
];
